[build]
  command = """
    cd netlify/functions && npm install && cd ../.. && \
    git clone https://github.com/flutter/flutter.git -b stable && \
    export PATH="$PATH:$PWD/flutter/bin" && \
    flutter precache && \
    flutter config --enable-web && \
    flutter pub get && \
    flutter build web --release
  """
  publish = "build/web"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  FLUTTER_VERSION = "stable"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200