[build]
  command = "npm install && cd functions && npm install"
  functions = "netlify/functions"
  publish = "build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200