// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANJcyhrAXiS9J-2WCQvkrUgbtA4w1eMYQ',
    appId: '1:339812923803:web:9d4aad93ab736ffafe093e',
    messagingSenderId: '339812923803',
    projectId: 'my-lunch-app',
    authDomain: 'my-lunch-app.firebaseapp.com',
    storageBucket: 'my-lunch-app.firebasestorage.app',
    measurementId: 'G-HM0ZY518Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcjE95YxK7_1VqyBfCsiN1Pc4RtyOOyRk',
    appId: '1:339812923803:android:1d8776f247f51a64fe093e',
    messagingSenderId: '339812923803',
    projectId: 'my-lunch-app',
    storageBucket: 'my-lunch-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb9PmGgJdwDZZI-sGNauLnW6y6aDYCKRE',
    appId: '1:339812923803:ios:c4178457a6fc332efe093e',
    messagingSenderId: '339812923803',
    projectId: 'my-lunch-app',
    storageBucket: 'my-lunch-app.firebasestorage.app',
    iosBundleId: 'com.example.myLunchApp',
  );
}
